# Generated by Django 4.2.30 on 2026-09-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_name', models.CharField(max_length=255)),
                ('farm_area', models.DecimalField(decimal_places=4, max_digits=10)),
                ('farm_area_unit', models.CharField(choices=[('ha', 'Hectare'), ('acre', 'Acre'), ('sqm', 'Square Meter'), ('guntha', 'Guntha'), ('bigha', 'Bigha'), ('other', 'Other')], default='acre', max_length=10)),
                ('irrigation_type', models.CharField(choices=[('rain_fed', 'Rain-fed'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('other', 'Other')], default='rain_fed', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('locality', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.farmerprofile')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ['-created_at'],
            },
        ),
    ]
