# Generated by Django 4.2.30 on 2026-09-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display/sort order within a crop type lifecycle.')),
                ('description', models.TextField(blank=True, help_text='Brief description of what happens during this stage.')),
                ('crop_type', models.CharField(blank=True, help_text='Null = generic stage applicable to all crops. Set to a crop name (e.g. "wheat") for crop-specific stages.', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Growth Stage',
                'verbose_name_plural': 'Growth Stages',
                'ordering': ['crop_type', 'order'],
                'unique_together': {('name', 'crop_type')},
            },
        ),
        migrations.CreateModel(
            name='CropProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(blank=True, help_text='e.g., HD 2967 for wheat, Pusa Basmati 1121 for rice.', max_length=100)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, help_text='May be left blank at sowing time.', null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peat', 'Peat'), ('chalk', 'Chalk'), ('black', 'Black (Regur)'), ('alluvial', 'Alluvial'), ('other', 'Other')], max_length=20)),
                ('cultivation_method', models.CharField(blank=True, choices=[('conventional', 'Conventional'), ('organic', 'Organic'), ('hydroponic', 'Hydroponic'), ('mixed', 'Mixed'), ('zero_tillage', 'Zero Tillage'), ('other', 'Other')], max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
                ('growth_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='crops.growthstage')),
            ],
            options={
                'verbose_name': 'Crop Profile',
                'verbose_name_plural': 'Crop Profiles',
                'ordering': ['-sowing_date'],
            },
        ),
    ]
