# Generated by Django 4.2.30 on 2026-10-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where reading was taken (defaults to farm latitude).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where reading was taken (defaults to farm longitude).', max_digits=9, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='UTC timestamp of measurement.')),
                ('moisture', models.FloatField(help_text='Soil moisture reading as a numerical value.')),
                ('unit', models.CharField(choices=[('PERCENT', 'Percent')], default='PERCENT', help_text='Unit of moisture measurement.', max_length=20)),
                ('depth', models.PositiveIntegerField(default=20, help_text='Depth in centimeters (e.g. 5, 20, 50 cm). Non-negative integer.')),
                ('source', models.CharField(choices=[('SENSOR', 'Sensor'), ('SATELLITE', 'Satellite'), ('REANALYSIS', 'Reanalysis'), ('ESTIMATED', 'Estimated')], default='SENSOR', help_text='Data source provider type.', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score between 0.0 and 1.0 (null if uncalibrated/unavailable).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_records', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Soil Moisture Record',
                'verbose_name_plural': 'Soil Moisture Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['farm', '-timestamp'], name='soil_soilmo_farm_id_da232c_idx'), models.Index(fields=['farm', 'depth', '-timestamp'], name='soil_soilmo_farm_id_f187a9_idx'), models.Index(fields=['farm', 'source', '-timestamp'], name='soil_soilmo_farm_id_9a8bf9_idx')],
                'unique_together': {('farm', 'timestamp', 'depth', 'source')},
            },
        ),
    ]
