# Generated by Django 4.2.30 on 2026-09-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('apparent_temperature', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('rain', models.FloatField(blank=True, null=True)),
                ('relative_humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('surface_pressure', models.FloatField(blank=True, null=True)),
                ('evapotranspiration', models.FloatField(blank=True, null=True)),
                ('precipitation_probability', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('OPEN_METEO', 'Open-Meteo')], default='OPEN_METEO', max_length=20)),
                ('forecast_type', models.CharField(choices=[('CURRENT', 'Current Weather'), ('HOURLY_FORECAST', 'Hourly Forecast'), ('DAILY_FORECAST', 'Daily Forecast'), ('HISTORICAL', 'Historical')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='farms.farm')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['farm', 'forecast_type', 'timestamp'], name='weather_wea_farm_id_9f36ae_idx')],
                'unique_together': {('farm', 'timestamp', 'forecast_type', 'source')},
            },
        ),
    ]
